### PR TITLE
Added support for Visual Studio 2022

### PR DESCRIPTION
**Pull request by VAllens**
Added support for Visual Studio 2022

### CODE REVIEW

**Comment by VAllens** [comment]
image
[TODOHighlighter.VS2022.vsix.zip](https://github.com/HumanGamer/TODOHighlighter/files/8228855/TODOHighlighter.VS2022.vsix.zip)

**Comment by ratkingsminion** [comment]
Can this please also support TODO without the colon?

**Comment by VAllens** [comment]
> Can this please also support TODO without the colon?

The colon is the key to trigger highlighting

**Comment by ratkingsminion** [comment]
I'm just proposing to remove the `+ ":"` at https://github.com/HumanGamer/TODOHighlighter/blob/master/TODOHighlighter/Classifier.cs#L105=

**Comment by mantasdaskevdev** [comment]
Hello, wanted to ask, when will be the merge? :D I really liked this on VS 2019 and I really missing it on VS 2022

**Comment by HumanGamer** [comment]
Oh I somehow never noticed this PR. Merging now.

**Comment by VAllens** [comment]
@HumanGamer 
Thank you very much. 
When will it be released to Visual Studio Marketplace?

https://marketplace.visualstudio.com/items?itemName=HumanGamer.todohighlighter

**Comment by mantasdaskev** [comment]
> @HumanGamer Thank you very much. When will it be released to Visual Studio Marketplace?
> 
> https://marketplace.visualstudio.com/items?itemName=HumanGamer.todohighlighter

I am interested in this too :D Of course there is no problem using it zipped but y'know :D

**Pull request merged**
